# Generated by Django 4.0.6 on 2022-07-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_matches_results'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
