# Generated by Django 4.0.6 on 2022-07-08 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_rename_results_matches_alter_matches_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.teams'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.teams'),
        ),
        migrations.CreateModel(
            name='PersonalResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.CharField(max_length=254)),
                ('home_team_score', models.IntegerField(blank=True, null=True)),
                ('away_team_score', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.teams')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.teams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
