# Generated by Django 4.0.6 on 2022-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_matches_away_team_alter_matches_home_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalresults',
            options={'verbose_name_plural': 'PersonalResults'},
        ),
        migrations.AddField(
            model_name='matches',
            name='group',
            field=models.CharField(blank=True, max_length=154, null=True),
        ),
    ]
