# Generated by Django 4.0.6 on 2022-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_personalresults_options_matches_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalresults',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalresults',
            name='group',
            field=models.CharField(blank=True, max_length=154, null=True),
        ),
    ]
