# Generated by Django 4.0.6 on 2022-08-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_personalresults_date_personalresults_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_number',
            field=models.IntegerField(),
        ),
    ]
