# Generated by Django 4.0.6 on 2022-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_crest_teams_crest_url_teams_abbreviated_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalresults',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
