# Generated by Django 4.0.6 on 2022-09-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_teams_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='home.teams'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='home.teams'),
        ),
    ]
