# Generated by Django 4.0.6 on 2022-10-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_team_id_wizard_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizard',
            name='team',
        ),
        migrations.AddField(
            model_name='wizard',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teams'),
        ),
        migrations.AddField(
            model_name='wizard',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teams'),
        ),
        migrations.AddField(
            model_name='wizard',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teams'),
        ),
    ]
