# Generated by Django 4.0.6 on 2022-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_wizard_team_wizard_away_team_wizard_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard',
            name='group',
            field=models.CharField(blank=True, max_length=154, null=True),
        ),
    ]
