# Generated by Django 4.0.6 on 2022-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_personalresults_match_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='match_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
