# Generated by Django 4.0.6 on 2022-10-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_wizard_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_team', to='home.teams'),
        ),
    ]
