# Generated by Django 4.0.6 on 2022-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_grouppositions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppositions',
            options={'verbose_name_plural': 'GroupPositions'},
        ),
        migrations.AddField(
            model_name='teams',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
