# Generated by Django 4.0.6 on 2022-11-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_grouppositions_options_teams_is_eliminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='is_eliminated_L16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='is_eliminated_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='is_eliminated_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='is_eliminated_qf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='is_eliminated_sf',
            field=models.BooleanField(default=False),
        ),
    ]
