# Generated by Django 4.0.6 on 2022-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_teams_is_eliminated_l16_teams_is_eliminated_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='is_in_final',
            field=models.BooleanField(default=False),
        ),
    ]
