# Generated by Django 4.0.6 on 2023-01-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_teams_is_in_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=154, null=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teams')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teams')),
            ],
        ),
    ]
