# Generated by Django 4.0.6 on 2023-01-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_defaultgrouppositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultwizard',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.teams'),
        ),
    ]
