# Generated by Django 4.0.6 on 2023-05-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_defaultmatches_delete_defaultwizard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmatches',
            name='match_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
