# Generated by Django 4.0.6 on 2023-07-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_venues_matches_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultmatches',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.venues'),
        ),
        migrations.AddField(
            model_name='personalresults',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.venues'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.venues'),
        ),
    ]
